name: domainion
version: 0.1.0

dependencies:
  - base
  - newtype-generics == 0.5.4
  - lens == 4.19.2
  - indexed-extras == 0.2
  - indexed == 0.1.3
  - transformers
  - mtl

executable:
  main: Main.hs
  source-dirs: src
